# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ijara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SDWebImage', '~> 5.0'
pod "SCPageControl"
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'IQKeyboardManager'
pod 'lottie-ios'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'FirebaseFirestore'
pod 'FSCalendar'

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.3'
               end
          end
   end
end
end
