# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ijara' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'IQKeyboardManager'
pod 'lottie-ios'
pod 'Alamofire'
pod 'SwiftyJSON'

end
